pipeline {
    agent any

    environment {
        IMAGE_NAME = "email-service"
        DOCKER_HUB_REPO = "rous2m"
        DOCKER_USERNAME = "rous2m"
        DOCKER_PASSWORD = "dckr_pat_7WJbOsXtkOuDrNmvBfir5sRgkBw"
        
        
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('emailService'){
                   script {
                    docker.image('maven:3.9.6-eclipse-temurin-17').inside {
                        sh 'mvn clean package -DskipTests'
                    }
                }
                }
            }
        }

        stage('Test') {
            steps {
                dir('emailService'){
                  script {
                    docker.image('maven:3.9.6-eclipse-temurin-17').inside {
                        sh 'mvn test'
                    }
                }
            }
            }
        }

        stage('Docker Build') {
            steps {
                dir('emailService') {
                    sh "docker build -t $DOCKER_HUB_REPO/$IMAGE_NAME:latest ."
                }
            }
        }

        stage('Deploy to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-hub-creds',
                    usernameVariable: 'rous2m',
                    passwordVariable: 'dckr_pat_deSAaaofo9aVPMnPKLnOnbxanbg'
                )]) {
                    sh '''
                        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                        docker push $DOCKER_USERNAME/$IMAGE_NAME:latest
                        docker logout
                    '''
                }
            }
        }
    }
}
