global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'movie-service'
    static_configs:
      - targets: ['localhost:8081']

  - job_name: 'user-service'
    static_configs:
      - targets: ['localhost:8082']
  
  - job_name: 'email-service'
    static_configs:
      - targets: ['localhost:8083']

