server:
  port: 8082

spring:
  application:
    name: userService

  ## MongoDB Properties
  data:
    mongodb:
      database: user
      port: 27017
      host: localhost
      auto-index-creation: true

  ## Zipkin and Sleuth Properties
  zipkin:
    base-url: http://localhost:9411

  sleuth:
    sampler:
      probability: 1.0

## Eureka Properties
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

# JWT Properties
jwt:
  secret:
    key: secret_secret_secret_secret_secret_secret_secret_secret_secret_secret

# Management and Prometheus Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    enable:
      jvm: true
      process: true
  endpoint:
    prometheus:
      enabled: true

  prometheus:
    metrics:
      export:
        enabled: true
