pipeline {
    agent any

    environment {
        IMAGE_NAME = "movie-service"
        DOCKER_HUB_REPO = "rous2m"
        DOCKER_USERNAME = "rous2m"
        DOCKER_PASSWORD = "dckr_pat_7WJbOsXtkOuDrNmvBfir5sRgkBw"
        
        
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('movieService'){
                   script {
                    docker.image('maven:3.9.6-eclipse-temurin-17').inside {
                        sh 'mvn clean package -DskipTests'
                    }
                }
              }
            }
        }

        stage('Test') {
            steps {
                dir('movieService') {
                   script {
                    docker.image('maven:3.9.6-eclipse-temurin-17').inside {
                        sh 'mvn test'
                    }
                }
              }
            }
        }

        stage('Docker Build') {
            steps {
                dir('movieService') {
                    sh "docker build -t $DOCKER_HUB_REPO/$IMAGE_NAME:latest ."
                }
            }
        }

        stage('Deploy to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-hub-creds',
                    usernameVariable: 'rous2m',
                    passwordVariable: 'dckr_pat_deSAaaofo9aVPMnPKLnOnbxanbg'
                )]) {
                    sh '''
                        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                        docker push $DOCKER_USERNAME/$IMAGE_NAME:latest
                        docker logout
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG_FILE')]) {
                    sh '''
                    apt-get update && \
                    apt-get install -y ca-certificates curl gnupg && \
                    install -m 0755 -d /etc/apt/keyrings && \
                    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg && \
                    chmod 0644 /etc/apt/keyrings/kubernetes-archive-keyring.gpg && \
                    echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /" > /etc/apt/sources.list.d/kubernetes.list && \
                    apt-get update && \
                    apt-get install -y kubectl
                        export KUBECONFIG=$KUBECONFIG_FILE
                        kubectl apply -f k8s/movie-deployment.yml

                    '''
                }
            }
        }
    }
}
